{
 "title": "Speedgraphs - Test",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## \r\n### ⠀![Image](https://static3.pisapapeles.net/uploads/2019/03/cropped-cropped-logosoloblanco512x512v2-32x32.png) Speedgraphs"
   }
  },
  { "title": "Operador 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "↱↲ Ping a servicios - Operador 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"heartbeat_amazon\" or r[\"entity_id\"] == \"heartbeat_apple\" or r[\"entity_id\"] == \"heartbeat_cern\" or r[\"entity_id\"] == \"heartbeat_cloudflare\" or r[\"entity_id\"] == \"heartbeat_facebook\" or r[\"entity_id\"] == \"heartbeat_google\" or r[\"entity_id\"] == \"heartbeat_instagram\" or r[\"entity_id\"] == \"heartbeat_microsoft\" or r[\"entity_id\"] == \"heartbeat_pisapapeles\" or r[\"entity_id\"] == \"heartbeat_spacex\" or r[\"entity_id\"] == \"heartbeat_starlink\" or r[\"entity_id\"] == \"heartbeat_tesla\" or r[\"entity_id\"] == \"heartbeat_tiktok\" or r[\"entity_id\"] == \"heartbeat_twitter\" or r[\"entity_id\"] == \"heartbeat_whatsapp\" or r[\"entity_id\"] == \"heartbeat_youtube\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"round_trip_time_max\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"units\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "↱↲ Ping a servicios - Operador 1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"heartbeat_amazon\" or r[\"entity_id\"] == \"heartbeat_apple\" or r[\"entity_id\"] == \"heartbeat_cern\" or r[\"entity_id\"] == \"heartbeat_cloudflare\" or r[\"entity_id\"] == \"heartbeat_facebook\" or r[\"entity_id\"] == \"heartbeat_google\" or r[\"entity_id\"] == \"heartbeat_instagram\" or r[\"entity_id\"] == \"heartbeat_microsoft\" or r[\"entity_id\"] == \"heartbeat_pisapapeles\" or r[\"entity_id\"] == \"heartbeat_spacex\" or r[\"entity_id\"] == \"heartbeat_starlink\" or r[\"entity_id\"] == \"heartbeat_tesla\" or r[\"entity_id\"] == \"heartbeat_tiktok\" or r[\"entity_id\"] == \"heartbeat_twitter\" or r[\"entity_id\"] == \"heartbeat_whatsapp\" or r[\"entity_id\"] == \"heartbeat_youtube\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"round_trip_time_max\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"units\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "🡇 Descarga - Operador 1",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"download_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"download_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"fast_com_download\" or r[\"entity_id\"] == \"speedtest_download\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "🡅 Carga - Operador 1",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"upload_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"upload_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"speedtest_upload\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "🡅 Carga (Máximo) - Operador 1",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"upload_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"upload_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"speedtest_upload\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "🡅 Carga (Promedio) - Operador 1",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"upload_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"upload_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"speedtest_upload\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "🡅 Carga (Mínimo) - Operador 1",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"upload_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"upload_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"speedtest_upload\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "🡇 Descarga (Máximo) - Operador 1",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"download_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"download_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"fast_com_download\" or r[\"entity_id\"] == \"speedtest_download\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "🡇 Descarga (Promedio) - Operador 1",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"download_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"download_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"fast_com_download\" or r[\"entity_id\"] == \"speedtest_download\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "🡇 Descarga (Mínimo) - Operador 1",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"download_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"download_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"fast_com_download\" or r[\"entity_id\"] == \"speedtest_download\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "↱↲ Ping Ookla Speedtest - Operador 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ms\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"speedtest_ping\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Operador 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ping a servicios - Operador 2",
     "type": "stat",
     "gridPos": { "h": 15, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test2\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"heartbeat_amazon\" or r[\"entity_id\"] == \"heartbeat_apple\" or r[\"entity_id\"] == \"heartbeat_cern\" or r[\"entity_id\"] == \"heartbeat_cloudflare\" or r[\"entity_id\"] == \"heartbeat_facebook\" or r[\"entity_id\"] == \"heartbeat_google\" or r[\"entity_id\"] == \"heartbeat_instagram\" or r[\"entity_id\"] == \"heartbeat_microsoft\" or r[\"entity_id\"] == \"heartbeat_pisapapeles\" or r[\"entity_id\"] == \"heartbeat_spacex\" or r[\"entity_id\"] == \"heartbeat_starlink\" or r[\"entity_id\"] == \"heartbeat_tesla\" or r[\"entity_id\"] == \"heartbeat_tiktok\" or r[\"entity_id\"] == \"heartbeat_twitter\" or r[\"entity_id\"] == \"heartbeat_whatsapp\" or r[\"entity_id\"] == \"heartbeat_youtube\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"round_trip_time_max\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"units\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"max\")"
      }
     ]
    },
    {
     "title": "Velocidad de descarga - Operador 2",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 16, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test2\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"download_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"download_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"fast_com_download\" or r[\"entity_id\"] == \"speedtest_download\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Operador 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Velocidad de descarga - Operador 3",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 16, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test3\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"download_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"download_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"fast_com_download\" or r[\"entity_id\"] == \"speedtest_download\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Ping a servicios - Operador 3",
     "type": "stat",
     "gridPos": { "h": 15, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test3\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"heartbeat_amazon\" or r[\"entity_id\"] == \"heartbeat_apple\" or r[\"entity_id\"] == \"heartbeat_cern\" or r[\"entity_id\"] == \"heartbeat_cloudflare\" or r[\"entity_id\"] == \"heartbeat_facebook\" or r[\"entity_id\"] == \"heartbeat_google\" or r[\"entity_id\"] == \"heartbeat_instagram\" or r[\"entity_id\"] == \"heartbeat_microsoft\" or r[\"entity_id\"] == \"heartbeat_pisapapeles\" or r[\"entity_id\"] == \"heartbeat_spacex\" or r[\"entity_id\"] == \"heartbeat_starlink\" or r[\"entity_id\"] == \"heartbeat_tesla\" or r[\"entity_id\"] == \"heartbeat_tiktok\" or r[\"entity_id\"] == \"heartbeat_twitter\" or r[\"entity_id\"] == \"heartbeat_whatsapp\" or r[\"entity_id\"] == \"heartbeat_youtube\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"round_trip_time_max\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"units\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"max\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Operador 4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ping a servicios - Operador 4",
     "type": "stat",
     "gridPos": { "h": 15, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test4\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"heartbeat_amazon\" or r[\"entity_id\"] == \"heartbeat_apple\" or r[\"entity_id\"] == \"heartbeat_cern\" or r[\"entity_id\"] == \"heartbeat_cloudflare\" or r[\"entity_id\"] == \"heartbeat_facebook\" or r[\"entity_id\"] == \"heartbeat_google\" or r[\"entity_id\"] == \"heartbeat_instagram\" or r[\"entity_id\"] == \"heartbeat_microsoft\" or r[\"entity_id\"] == \"heartbeat_pisapapeles\" or r[\"entity_id\"] == \"heartbeat_spacex\" or r[\"entity_id\"] == \"heartbeat_starlink\" or r[\"entity_id\"] == \"heartbeat_tesla\" or r[\"entity_id\"] == \"heartbeat_tiktok\" or r[\"entity_id\"] == \"heartbeat_twitter\" or r[\"entity_id\"] == \"heartbeat_whatsapp\" or r[\"entity_id\"] == \"heartbeat_youtube\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"round_trip_time_max\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"units\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"max\")"
      }
     ]
    },
    {
     "title": "Velocidad de descarga - Operador 4",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 16, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "query": "from(bucket: \"Testing\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"Test4\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"download_speedtest2_pisapapeleslabs_com\" or r[\"entity_id\"] == \"download_speedtest_pisapapeleslabs_com\" or r[\"entity_id\"] == \"fast_com_download\" or r[\"entity_id\"] == \"speedtest_download\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  { "title": "Comparativa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } }
 ]
}