{
 "title": "Speedtest Operadores - PisapapelesLabs",
 "tags": [
  "Pisapapeles Labs",
  "Producción"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Latencias/Ping promedio hacia sitios (HAOS-TestJZ-TestDB)",
   "type": "stat",
   "description": "Latencias hacia sitios web para el operador X, desde VM0.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HomeAssistant-Casa\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"heartbeat_youtube\" or r[\"entity_id\"] == \"heartbeat_whatsapp\" or r[\"entity_id\"] == \"heartbeat_twitter\" or r[\"entity_id\"] == \"heartbeat_tiktok\" or r[\"entity_id\"] == \"heartbeat_tesla\" or r[\"entity_id\"] == \"heartbeat_starlink\" or r[\"entity_id\"] == \"heartbeat_spacex\" or r[\"entity_id\"] == \"heartbeat_pisapapeles\" or r[\"entity_id\"] == \"heartbeat_instagram\" or r[\"entity_id\"] == \"heartbeat_google\" or r[\"entity_id\"] == \"heartbeat_amazon\" or r[\"entity_id\"] == \"heartbeat_apple\" or r[\"entity_id\"] == \"heartbeat_cern\" or r[\"entity_id\"] == \"heartbeat_cloudflare\" or r[\"entity_id\"] == \"heartbeat_facebook\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"round_trip_time_avg\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"units\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pruebas de velocidad (HAOS-TestJZ-TestDB)",
   "type": "timeseries",
   "description": "Pruebas de velocidad de carga y descarga de datos para el operador X, desde VM0.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeAssistant-Casa\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"fast_com_download\" or r[\"entity_id\"] == \"speedtest_download\" or r[\"entity_id\"] == \"speedtest_upload\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Mbit/s\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Latencias/Ping promedio hacia sitios (HAOS-TestJZ-TestDB)",
   "type": "timeseries",
   "description": "Latencias hacia sitios web para el operador X, desde VM0.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeAssistant-Casa\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"heartbeat_youtube\" or r[\"entity_id\"] == \"heartbeat_whatsapp\" or r[\"entity_id\"] == \"heartbeat_twitter\" or r[\"entity_id\"] == \"heartbeat_tiktok\" or r[\"entity_id\"] == \"heartbeat_tesla\" or r[\"entity_id\"] == \"heartbeat_starlink\" or r[\"entity_id\"] == \"heartbeat_spacex\" or r[\"entity_id\"] == \"heartbeat_pisapapeles\" or r[\"entity_id\"] == \"heartbeat_instagram\" or r[\"entity_id\"] == \"heartbeat_google\" or r[\"entity_id\"] == \"heartbeat_amazon\" or r[\"entity_id\"] == \"heartbeat_apple\" or r[\"entity_id\"] == \"heartbeat_cern\" or r[\"entity_id\"] == \"heartbeat_cloudflare\" or r[\"entity_id\"] == \"heartbeat_facebook\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"round_trip_time_avg\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"units\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Heartbeat/Ping Test - Google (Promedio)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HomeAssistant-Casa\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"heartbeat_google\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"round_trip_time_avg\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"units\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"binary_sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Heartbeat/Ping Test - Google (Actual)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HomeAssistant-Casa\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"heartbeat_google\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"round_trip_time_avg\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"units\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"binary_sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}