version: '3.3'
services:
    uptime-kuma:
        restart: always
        ports:
            - 3001:3001 
        volumes:
            - ./Data:/app/data
        container_name: PPLabs-UptimeKuma-Prod
        image: louislam/uptime-kuma:latest