###################################### Plantilla de Grafana ######################################

########## Documentación ###########
# https://grafana.com/docs/grafana #

version: '3.3'
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: PPLabs-Grafana-Prod
    network_mode: bridge
    ports:
      - 3000:3000
    volumes:
      - PPLabs-Grafana-Prod:/var/lib/grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_DOMAIN=grafana.example.com
      - GF_SERVER_ROOT_URL=https://grafana.example.com
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_RENDERING_SERVER_URL=http://0.0.0.0:8081/render
      - GF_RENDERING_CALLBACK_URL=https://grafana.example.com
      - GF_LOG_FILTERS=rendering:debug
    user: '104'

  renderer:
  ### Imagen oficial, solo disponible para x86 ###
    image: grafana/grafana-image-renderer:latest
    container_name: PPLabs-GrafanaImageRenderer-Prod
    network_mode: bridge
    ports:
      - 8081:8081

volumes:
    PPLabs-Grafana-Prod:
        external: true