version: '3.3'
services:
    wg-easy:
        image: weejewel/wg-easy
        container_name: PPLabs-WGEasy-Prod
        volumes:
            - ./Data:/etc/wireguard
        environment:
            - WG_HOST=0.0.0.0
            - PASSWORD=macoy123
        ports:
            - '51820:51820/udp'
            - '51821:51821/tcp'
        restart: unless-stopped
