###################################### Plantilla de WG-Easy ######################################

############# Documentación #################
# https://hub.docker.com/r/weejewel/wg-easy #

version: '3.3'
services:
    wg-easy:
        image: weejewel/wg-easy
        container_name: PPLabs-WGEasy-Prod
        network_mode: bridge
        volumes:
            - ./Data:/etc/wireguard
        environment:
            - WG_HOST=0.0.0.0
            - PASSWORD=macoy123
            - WG_DEFAULT_ADDRESS=10.8.0.x
            - WG_DEFAULT_DNS=1.1.1.1
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        ports:
            - '51820:51820/udp'
            - '51821:51821/tcp'
        restart: unless-stopped